defaults:
  - _self_
  - task: spell_word
  # - task: factory_pickitem

# name: resnet18
name: debug
config_name: brae_debug # Use this config name to load the default config from openpi repo

task_name: ${task.name}
shape_meta: ${task.shape_meta}
exp_name: "pi0_entangle_line"
collate_type: "pi0_entangle_line"

model:
  model_config:
    _target_: openpi.models.pi0_fast.Pi0FASTConfig
    action_dim: 14
    action_horizon: 20
    max_token_len: 250
  weight_loader:
    _target_: openpi.training.weight_loaders.CheckpointWeightLoader
    params_path: /x2robot/brae/projects/.cache/openpi/openpi-assets/checkpoints/pi0_fast_base/params
  data: # Use for inference data preprocessing
    _target_: openpi.training.config.LeRobotX2robotDataConfig
    repo_id: entangle-line
    base_config:
      _target_: openpi.training.config.DataConfig
      local_files_only: True
      asset_id: debug_test
  num_train_steps: 30_000

train_dataloader:
  batch_size: 8 # 32-5.1s/it 16-8s/it 8-3.5s/it

val_dataloader:
  batch_size: 8

# optimizer:
#   _target_: torch.optim.AdamW
#   lr: 2e-4
#   # lr: 1.9e-4
#   betas: [0.95, 0.999]
#   eps: 1.0e-8
#   weight_decay: 1.0e-6

training:
  device: "cuda"
  seed: 42
  debug: False
  # debug: True
  lr_scheduler: cosine
  lr_warmup_steps: 1000
  num_epochs: 150
  gradient_accumulate_every: 1
  # EMA destroys performance when used with BatchNorm
  # replace BatchNorm with GroupNorm.
  use_ema: False
  freeze_encoder: False
  freeze_lm_encoder: False
  # training loop control
  # in epochs
  rollout_every: 1
  checkpoint_every: 5
  val_every: 5
  sample_every: 5
  # steps per epoch
  max_train_steps: null
  max_val_steps: null
  # misc
  tqdm_interval_sec: 1.0
  resume: False
  fsdp_devices: 1
  # resume: True
  # resume_ckpt_path: '/x2robot/ganruyi/workspace/diffusion_policy/2025.02.07/17.21.43_resnet18_colorjiter_478_pick_waste_hist2s/checkpoints/epoch=0050-train_loss=0.001.ckpt'  

logging:
  # project: diffusion_policy_debug
  project: entangle_ablations
  resume: False
  mode: online
  name: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}
  tags: ["${name}", "${task_name}", "${exp_name}"]
  id: null
  group: null

checkpoint:
  topk:
    monitor_key: train_loss
    mode: min
    k: 10
    format_str: 'epoch={epoch:04d}-train_loss={train_loss:.3f}.ckpt'
  save_last_ckpt: True
  save_last_snapshot: False
  keep_period: 5000
  checkpoint_dir: ${multi_run.run_dir}

multi_run:
  run_dir: /x2robot/brae/projects/openpi/checkpoints/initial_test/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  wandb_name_base: ${name}_${task_name}_${now:%Y.%m.%d-%H.%M.%S}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: ${multi_run.run_dir} 
  # sweep:
  #   dir: /x2robot/ganruyi/workspace/diffusion_policy/${now:%H.%M.%S}_${name}_${task_name}
  #   subdir: ${hydra.job.num}
